Hw3
KatarinaAet/Android-course2019 pull request #3
Opened 2019-10-20 12:34 UTC by KatarinaAet

Implement list of notes using Recycler View

2019-10-20 14:17 UTC, IvanShafran requested changes
Круто сделано) Поправь замечания, пожалуйста, или ответь, где не согласна

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/build.gradle
> +dependencies {
Блок dependencies задублирован почему-то. Оставь один и убери одинаковые строки, пожалуйста

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/java/com/github/KatarinaAet/myfirstapplication/MainActivity.java
> +        recyclerView.getRecycledViewPool().setMaxRecycledViews(0, 3);
Не уверен, что 3 это достаточно. Чтобы проверить это можешь сделать так:
- Запустить приложение в режиме Debug
- Скролить список верх и вниз некоторое время
- Поставить breakpoint в метод onCreateViewHolder
- Продолжть скроллить
Если breakpoint будет срабатывать, то число нужно увеличить. Если не будет, то всё хорошо

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/java/com/github/KatarinaAet/myfirstapplication/MainActivity.java
> +        recyclerView.getRecycledViewPool().setMaxRecycledViews(0, 3);
Скорее всего достаточно, у меня на для 2 уже работало.
Кстати, можно и без breakpoint-ов проверять. В логи писать

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/java/com/github/KatarinaAet/myfirstapplication/NoteRepository.java
> +    private static final Map<String, Note> NOTE_LIST = new LinkedHashMap<>();
Можно и просто HashMap. Linked здесь никак не помогает или помогает?

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/java/com/github/KatarinaAet/myfirstapplication/NoteRepository.java
> +    public NoteRepository(final Context context) {
Когда делают статический класс, то конструктор не используют чаще всего.
Код из конструктора лучше перенести в статический метод "init", например.
А конструктор можно сделать приватным вообще(и пустым), чтобы никто случайно не вызвал.

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/res/layout/activity_note_list.xml
> +        android:layout_width="wrap_content"
В прошлый раз не заметил, но wrap_content для ImageView редко используют, т.к. картинки бывают сильно разные по размеру.
Обычно высоту или ширину задают жестко или в зависимости от размера экрана. 
Для элемента списка задают жестко. По разметке в Figma - это 96 dp на 96dp, если не ошибаюсь

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/res/layout/activity_note_list.xml
> +android:layout_height="wrap_content"
Высоту элемента списка лучше задавать жестко, чтобы не тратилось время на вычисления его размера

2019-10-20 14:17 UTC, IvanShafran commented on MyFirstApplication/app/src/main/res/layout/activity_note1.xml
>          android:layout_width="wrap_content"
В прошлый раз не заметил, но wrap_content для ImageView редко используют, т.к. картинки бывают сильно разные по размеру.
Обычно высоту или ширину задают жестко или в зависимости от размера экрана. 
Для этого экрана ширина должна быть match_parent с margin слева и справа в 16 dp, например.
Высота должна быть в половину экрана по разметке. Для этого layout_height выставляем в 0dp, а размеры будут определяться весом в LinearLayout

2019-10-21 19:27 UTC, KatarinaAet commented
LinkedHashMap позволяет сделать заметки упорядоченными(Peak1, Peak2...)
c HashMap они идут в порядке: Peak1, Peak3, Peak2...

2019-10-21 19:31 UTC, KatarinaAet commented
Проверила с 3 в порядке всё.

2019-10-21 19:32 UTC, KatarinaAet commented
Проверила с 3 пулами в дебаге-в порядке всё.

2019-10-21 20:24 UTC, IvanShafran approved these changes
Отличная работа :)

2019-10-21 20:24 UTC, merged